package cz.cvut.fel.nss.booking.service;

import cz.cvut.fel.nss.booking.kafka.BookingEventPublisher;
import cz.cvut.fel.nss.booking.dao.BookingDao;
import cz.cvut.fel.nss.booking.dto.booking.BookingDto;
import cz.cvut.fel.nss.booking.dto.booking.BookingPersonDTO;
import cz.cvut.fel.nss.booking.dto.booking.BookingReservationDTO;
import cz.cvut.fel.nss.booking.dto.booking.CreateBookingDTO;
import cz.cvut.fel.nss.booking.dto.mapper.BookingMapper;
import cz.cvut.fel.nss.exception.NotFoundException;
import cz.cvut.fel.nss.booking.BookingManagerFacade;
import cz.cvut.fel.nss.booking.status.BookingStateFactory;
import cz.cvut.fel.nss.booking.entity.Booking;
import cz.cvut.fel.nss.booking.entity.BookingStatus;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Handles booking lifecycle operations such as creation, lookup and cancellation.
 * The service owns booking persistence and publishes booking-related domain events.
 */
@Service
@Transactional
public class BookingService {

    private static final Logger log = LoggerFactory.getLogger(BookingService.class);

    private final BookingDao bookingDao;
    private final BookingMapper bookingMapper;
    private final BookingEventPublisher bookingEventPublisher;
    private final BookingManagerFacade bookingManagerFacade;

    public BookingService(BookingDao bookingDao,
                          BookingMapper bookingMapper,
                          BookingEventPublisher bookingEventPublisher,
                          BookingManagerFacade bookingManagerFacade) {
        this.bookingDao = bookingDao;
        this.bookingMapper = bookingMapper;
        this.bookingEventPublisher = bookingEventPublisher;
        this.bookingManagerFacade = bookingManagerFacade;
    }

    /**
     * Creates a booking from client input and updates dependent services.
     *
     * @param dto booking creation request
     * @return persisted booking with generated identifiers and calculated price
     */
    public Booking createBookingFromDto(CreateBookingDTO dto) {
        validateCreateBookingDto(dto);

        // Use Facade to prepare the Booking entity
        final Booking booking = bookingManagerFacade.initializeBooking(dto);

        // 1. First save to DB so booking has ID
        bookingDao.save(booking);

        // 2. Then finalize (external calls to accommodation service using valid booking ID)
        bookingManagerFacade.finalizeBooking(booking, dto);

        // 3. Update booking to save reservationIds
        final Booking managedBooking = bookingDao.update(booking);

        // Refresh to get booking number generated by database
        bookingDao.refresh(managedBooking);

        // 4. Last step - notify Kafka about tour capacity change
        bookingEventPublisher.publishTourCapacityChanged(
                managedBooking.getId(),
                managedBooking.getTourId(),
                -managedBooking.getPersonIds().size()
        );
        log.info("Booking created with id: {}, total price: {}", managedBooking.getId(), managedBooking.getTotalPrice());

        return bookingDao.find(managedBooking.getId());
    }

    private void validateCreateBookingDto(CreateBookingDTO dto) {
        if (dto == null) {
            throw new IllegalArgumentException("CreateBookingDTO must not be null");
        }
        if (dto.tourId() == null) {
            throw new IllegalArgumentException("Booking must have tourId");
        }
        if (dto.persons() == null || dto.persons().isEmpty()) {
            throw new IllegalArgumentException("Booking must have at least one person");
        }
        if (dto.reservations() == null || dto.reservations().isEmpty()) {
            throw new IllegalArgumentException("Booking must have at least one reservation");
        }

        for (BookingPersonDTO person : dto.persons()) {
            if (person == null) {
                throw new IllegalArgumentException("Person must not be null");
            }
            if (person.id() == null) {
                if (person.firstName() == null || person.firstName().isBlank()) {
                    throw new IllegalArgumentException("Person firstName must not be null or blank");
                }
                if (person.lastName() == null || person.lastName().isBlank()) {
                    throw new IllegalArgumentException("Person lastName must not be null or blank");
                }
                if (person.dateOfBirth() == null) {
                    throw new IllegalArgumentException("Person dateOfBirth must not be null");
                }
                if (person.dateOfBirth().isAfter(LocalDate.now())) {
                    throw new IllegalArgumentException("Person dateOfBirth cannot be in the future");
                }
            }
        }

        for (BookingReservationDTO res : dto.reservations()) {
            if (res == null) {
                throw new IllegalArgumentException("Reservation must not be null");
            }
            if (res.accommodationId() == null) {
                throw new IllegalArgumentException("Reservation accommodationId must not be null");
            }
            if (res.startDate() == null) {
                throw new IllegalArgumentException("Reservation startDate must not be null");
            }
            if (res.endDate() == null) {
                throw new IllegalArgumentException("Reservation endDate must not be null");
            }
            if (res.startDate().isAfter(res.endDate())) {
                throw new IllegalArgumentException("Reservation startDate cannot be after endDate");
            }
        }
    }

    /**
     * Finds a booking by its id.
     *
     * @param id booking id
     * @return booking entity
     * @throws NotFoundException when the booking does not exist
     */
    public Booking findById(Long id) {
        Objects.requireNonNull(id);
        final Booking booking = bookingDao.find(id);
        if (booking == null) {
            throw new NotFoundException("Booking not found: " + id);
        }
        return booking;
    }

    /**
     * Returns bookings created inside an inclusive date range.
     *
     * @param fromDate start of the creation date range
     * @param toDate end of the creation date range
     * @return booking DTOs created in the given period
     */
    public List<BookingDto> getBookingsCreatedBetween(LocalDate fromDate, LocalDate toDate) {
        if (fromDate == null || toDate == null || fromDate.isAfter(toDate)) {
            throw new IllegalArgumentException("Invalid date range");
        }
        return bookingDao.findBookingsCreatedBetween(fromDate, toDate).stream()
                .map(bookingMapper::bookingToBookingDto)
                .toList();
    }


    /**
     * Cancels all active bookings for a cancelled tour.
     *
     * @param tourId id of the tour whose bookings should be cancelled
     */
    public void cancelBookingByTour(Long tourId) {

        List<Booking> bookings = bookingDao.findAllByTour(tourId);

        for (Booking booking : bookings) {
            if (booking.getStatus() != BookingStatus.CANCELLED) {
                bookingEventPublisher.publishBookingCancelled(
                        booking.getId(),
                        tourId,
                        booking.getPersonIds().size()
                );

                BookingStateFactory.getState(booking.getStatus()).cancel(booking);
                bookingDao.update(booking);
            }
        }
    }


    /**
     * Finds bookings that contain a given user/person id.
     *
     * @param userId user/person id
     * @return matching booking DTOs
     */
    public List<BookingDto> findByUser(Long userId) {
        List<Booking> bookings = bookingDao.findByUser(userId);
        return bookings.stream().map(b -> bookingMapper.bookingToBookingDto(b)).collect(Collectors.toList());

    }
    // when we delete accommodation
    /**
     * Cancels a booking as a system action and restores tour capacity.
     *
     * @param id booking id
     */
    public void removeBookingByIdBySystem (Long id) {
        Booking booking = bookingDao.find(id);
        if (booking == null) {
            throw new NotFoundException("Booking not found: " + id);
        }
        if (booking.getStatus() == BookingStatus.CANCELLED) {
            return;
        }
        BookingStateFactory.getState(booking.getStatus()).cancel(booking);
        bookingDao.update(booking);
        bookingEventPublisher.publishTourCapacityChanged(
                booking.getId(),
                booking.getTourId(),
                booking.getPersonIds().size()
        );
    }

    /**
     * Cancels a booking requested by the user and notifies dependent services.
     *
     * @param id booking id
     */
    public void cancelBookingByUser(Long id) {
        Booking booking = bookingDao.find(id);
        if (booking == null) {
            return;
        }
        if (booking.getStatus() == BookingStatus.CANCELLED) {
            return;
        }
        BookingStateFactory.getState(booking.getStatus()).cancel(booking);
        bookingDao.update(booking);
        int personsCount = booking.getPersonIds().size();
        bookingEventPublisher.publishBookingCancelled(booking.getId(), booking.getTourId(), personsCount);
        bookingEventPublisher.publishTourCapacityChanged(booking.getId(), booking.getTourId(), personsCount);
    }
}




